In [1]:
import pandas as pd

In [18]:
df = pd.read_csv("C:/Users/asus/Desktop/data_bts/communes_with_coordinates_best.csv")

In [21]:
m = df[~(df['LATITUDE'].isna() | df['LONGITUDE'].isna())]
m

                COMMUNE          WILAYA   LATITUDE  LONGITUDE
0                REMCHI         TLEMCEN  35.061727  -1.431833
1              BENI SAF  AIN-TEMOUCHENT  35.302546  -1.382036
2        OUED EL ALLEUG           BLIDA  36.555837   2.789636
3              BOUDJIMA      TIZI-OUZOU  36.804707   4.148840
4              EL HAMMA       KHENCHELA  35.471604   7.085646
...                 ...             ...        ...        ...
1495              MZADA           SETIF  36.545870   5.083963
1497           KHERRATA           SETIF  36.193503   5.354971
1499  BOURAOUI BELHADEF           JIJEL  36.695535   6.095170
1500              KSABI      BÉNI ABBÈS  29.127030  -0.985660
1502      BENI BOUATTAB           CHLEF  35.990212   1.657264

[1287 rows x 4 columns]

In [22]:
m.to_csv("only_coordinates.csv", index=False)

In [6]:
import pandas as pd

# Dictionnaire des wilayas avec leurs IDs
wilaya_ids = {
    'ADRAR': 1,
    'CHLEF': 2,
    'LAGHOUAT': 3,
    'OUM EL-BOUAGHI': 4,
    'BATNA': 5,
    'BEJAIA': 6,
    'BISKRA': 7,
    'BECHAR': 8,
    'BLIDA': 9,
    'BOUIRA': 10,
    'TAMANRASSET': 11,
    'TEBESSA': 12,
    'TLEMCEN': 13,
    'TIARET': 14,
    'TIZI-OUZOU': 15,
    'ALGER': 16,
    'DJELFA': 17,
    'JIJEL': 18,
    'SETIF': 19,
    'SAIDA': 20,
    'SKIKDA': 21,
    'SIDI-BELABBES': 22,
    'ANNABA': 23,
    'GUELMA': 24,
    'CONSTANTINE': 25,
    'MEDEA': 26,
    'MOSTAGANEM': 27,
    'MSILA': 28,
    'MASCARA': 29,
    'OUARGLA': 30,
    'ORAN': 31,
    'EL-BAYADH': 32,
    'ILLIZI': 33,
    'BORDJ-BOU-ARRERIDJ': 34,
    'BOUMERDES': 35,
    'EL-TARF': 36,
    'TINDOUF': 37,
    'TISSEMSILT': 38,
    'EL-OUED': 39,
    'KHENCHELA': 40,
    'SOUK-AHRAS': 41,
    'TIPAZA': 42,
    'MILA': 43,
    'AIN-DEFLA': 44,
    'NAAMA': 45,
    'AIN-TEMOUCHENT': 46,
    'GHARDAIA': 47,
    'RELIZANE': 48,
    'TIMIMOUN': 49,
    'BORDJ BADJI MOKHTAR': 50,
    'OULED DJELLAL': 51,
    'BÉNI ABBÈS': 52,
    'IN SALAH': 53,
    'IN GUEZZAM': 54,
    'TOUGGOURT': 55,
    'DJANET': 56,
    "EL M'GHAÏER": 57,
    'EL MENIAÂ': 58
}

# Charger le CSV
df = pd.read_csv("only_coordinates.csv")

# Générer les lignes formatées
with open("formatted_communes_old.py", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        wilaya_upper = row["WILAYA"].upper()
        wilaya_id = wilaya_ids.get(wilaya_upper)
        if wilaya_id is not None:
            commune = row["COMMUNE"].title()
            latitude = row["LATITUDE"]
            longitude = row["LONGITUDE"]
            f.write(f'Commune(name="{commune}", latitude={latitude}, longitude={longitude}, wilaya_id={wilaya_id}),\n')

In [7]:
import pandas as pd

# Ton dict EXACTEMENT comme dans le CSV (copié tel quel, avec accents et tirets)
wilaya_ids = {
    'ADRAR': 1,
    'CHLEF': 2,
    'LAGHOUAT': 3,
    'OUM EL-BOUAGHI': 4,
    'BATNA': 5,
    'BEJAIA': 6,
    'BISKRA': 7,
    'BECHAR': 8,
    'BLIDA': 9,
    'BOUIRA': 10,
    'TAMANRASSET': 11,
    'TEBESSA': 12,
    'TLEMCEN': 13,
    'TIARET': 14,
    'TIZI-OUZOU': 15,
    'ALGER': 16,
    'DJELFA': 17,
    'JIJEL': 18,
    'SETIF': 19,
    'SAIDA': 20,
    'SKIKDA': 21,
    'SIDI-BELABBES': 22,
    'ANNABA': 23,
    'GUELMA': 24,
    'CONSTANTINE': 25,
    'MEDEA': 26,
    'MOSTAGANEM': 27,
    'MSILA': 28,
    'MASCARA': 29,
    'OUARGLA': 30,
    'ORAN': 31,
    'EL-BAYADH': 32,
    'ILLIZI': 33,
    'BORDJ-BOU-ARRERIDJ': 34,
    'BOUMERDES': 35,
    'EL-TARF': 36,
    'TINDOUF': 37,
    'TISSEMSILT': 38,
    'EL-OUED': 39,
    'KHENCHELA': 40,
    'SOUK-AHRAS': 41,
    'TIPAZA': 42,
    'MILA': 43,
    'AIN-DEFLA': 44,
    'NAAMA': 45,
    'AIN-TEMOUCHENT': 46,
    'GHARDAIA': 47,
    'RELIZANE': 48,
    'TIMIMOUN': 49,
    'OULED DJELLAL': 50,
    'BORDJ BADJI MOKHTAR': 51,
    'BÉNI ABBÈS': 52,
    'IN SALAH': 53,
    'IN GUEZZAM': 54,
    'TOUGGOURT': 55,
    'DJANET': 56,
    "EL M'GHAÏER": 57,
    'EL MENIAÂ': 58
}

# Charger le CSV
df = pd.read_csv("only_coordinates.csv")

# Écriture dans le fichier de sortie
with open("formatted_communes.py", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        wilaya_raw = row["WILAYA"]
        wilaya_id = wilaya_ids.get(wilaya_raw)

        if wilaya_id is not None:
            commune = row["COMMUNE"]
            latitude = row["LATITUDE"]
            longitude = row["LONGITUDE"]
            f.write(f'Commune(name="{commune}", latitude={latitude}, longitude={longitude}, wilaya_id={wilaya_id}),\n')
        else:
            print(f"❌ Wilaya non trouvée : {wilaya_raw}")